#pragma once
#include <iostream>
#include <clocale>
#include <cwchar>
#include <tchar.h>
#include <fstream>
#include <ctime>
#include <iomanip>
#include <stack>
#include "In.h"
#include "Error.h"
#include "Parm.h"
#include "Log.h"
#include "Out.h"
#include "Graphs.h"
#include "FST.h"
#include "IT.h"
#include "LT.h"
#include "LexemaAnalysis.h"
#include "GRB.h"
#include "MFST.h"
using namespace std;